spring:
  jpa:
    mapping-resources:
      - META-INF/orm/directory/TreeNode.orm.xml
      - META-INF/orm/ticket/TicketSegment.orm.xml
      - META-INF/orm/draft/Version.orm.xml
      - META-INF/orm/draft/Draft.orm.xml
      - META-INF/orm/draft/Template.orm.xml
      - META-INF/orm/resource/Resource.orm.xml
      - META-INF/orm/resource/File.orm.xml